### PR TITLE
Fixed @types/jest error on compiling angular v2 generated project

### PR DESCRIPTION
**Pull request by sayuthisobri**
Hi @tinesoft, 

Changes on `package.json` template.
Change  @types/jest version based on `ngVersionMin`.

### CODE REVIEW

**Comment by tinesoft** [comment]
Thanks again mate!

How did you pin point the right `@types/jest` version for ng2 builds?

**Comment by sayuthisobri** [comment]
I do some test project and check @types/jest/index.d.ts file. Most of the build use the syntax for `Typescript 2.1+` which is not supported using Ng 2 compiler since its bundle with old tsc i guest. Correct me of i wrong :cold_sweat:

**Comment by sayuthisobri** [comment]
I do some test project and check @types/jest/index.d.ts file. Most of the build use the syntax for `Typescript 2.1+` which is not supported using Ng 2 compiler since its bundle with old tsc i guest. Correct me of i wrong :cold_sweat:

**Comment by sayuthisobri** [comment]
I do some test project and check @types/jest/index.d.ts file. Most of the build use the syntax for `Typescript 2.1+` which is not supported using Ng 2 compiler since its bundle with old tsc i guest. Correct me of i wrong :cold_sweat:

**Comment by sayuthisobri** [comment]
I do some test project and check @types/jest/index.d.ts file. Most of the build use the syntax for `Typescript 2.1+` which is not supported using Ng 2 compiler since its bundle with old tsc i guest. Correct me of i wrong :cold_sweat:

**Pull request merged**
